/* Generated By:JavaCC: Do not edit this line. PracticeTreeConstants.java Version 7.0.13 */
public interface PracticeTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
  };
}
/* JavaCC - OriginalChecksum=fa440f70a0a407c8ccc497a6b85d2943 (do not edit this line) */
