/* Generated By:JavaCC: Do not edit this line. LangTreeConstants.java Version 7.0.13 */
public interface LangTreeConstants
{
  public int JJTSTART = 0;
  public int JJTADDITIVEEXPRESSION = 1;
  public int JJTMULTIPLICATIVEEXPRESSION = 2;
  public int JJTIDENTIFIER = 3;


  public String[] jjtNodeName = {
    "Start",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=6ce0bc9e70abc37bed17fdaf8d0658ce (do not edit this line) */
