/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 7.0 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SimpleNode implements Node {

  protected Node parent;
  protected Node[] children;
  protected int id;
  protected Object value;
  protected Lang parser;

  public SimpleNode(int i) {
    id = i;
  }

  public SimpleNode(Lang p, int i) {
    this(i);
    parser = p;
  }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }

  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() {
    return LangTreeConstants.jjtNodeName[id];
  }
  public String toString(String prefix) { return prefix + toString(); }

  /* Override this method if you want to customize how the node dumps
     out its children. */

    // public void dump(String prefix) {
    //   System.out.println(toString(prefix));
    //   if (children != null) {
    //     for (int i = 0; i < children.length; ++i) {
    //       SimpleNode n = (SimpleNode)children[i];
    //       System.out.println("The Token Value is: " + n.value + " ");
    //       if (n != null) {
    //         n.dump(prefix + " ");
    //       }
    //     }
    //   }
    // }
    
    public void dump(String prefix) {
    // Print current node with its value (if available)
      System.out.print(toString(prefix));
      if (value != null) {
          System.out.println(" [" + value + "]");
      } else {
          System.out.println();
      }

        // Recursively print children with increased indentation
        if (children != null) {
            for (int i = 0; i < children.length; ++i) {
                if (children[i] != null) {
                    SimpleNode child = (SimpleNode) children[i];
                    child.dump(prefix + "  "); // Two spaces for indentation
                }
            }
        }
  }

  public int getId() {
    return id;
  }
}

/* JavaCC - OriginalChecksum=59dc2f6cd4cd37ffd30384d7ea95d76b (do not edit this line) */
