/* Generated By:JavaCC: Do not edit this line. LangTreeConstants.java Version 7.0.13 */
public interface LangTreeConstants
{
  public int JJTSTART = 0;
  public int JJTASSIGNMENT = 1;
  public int JJTLHS = 2;
  public int JJTRHS = 3;
  public int JJTADDITIVEEXPRESSION = 4;
  public int JJTMULTIPLICATIVEEXPRESSION = 5;
  public int JJTIDENTIFIER = 6;


  public String[] jjtNodeName = {
    "Start",
    "Assignment",
    "LHS",
    "RHS",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=78cb78285a45649d2bbe9e7f626089cc (do not edit this line) */
