/* Generated By:JavaCC: Do not edit this line. NumberParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NumberParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FLOAT = 6;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int DOUBLE = 8;
  /** RegularExpression Id. */
  int SEMICOLON = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int IDENTIFIER = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"float\"",
    "\"int\"",
    "\"double\"",
    "\";\"",
    "\",\"",
    "<IDENTIFIER>",
  };

}
