/* Generated By:JavaCC: Do not edit this line. MiniLangTreeConstants.java Version 7.0.13 */
public interface MiniLangTreeConstants
{
  public int JJTSTART = 0;
  public int JJTASSIGNMENT = 1;
  public int JJTVARIABLE = 2;
  public int JJTEXPRESSION = 3;
  public int JJTTERM = 4;


  public String[] jjtNodeName = {
    "Start",
    "Assignment",
    "Variable",
    "Expression",
    "Term",
  };
}
/* JavaCC - OriginalChecksum=6c2f8362a6dc0af292b23830c25383d3 (do not edit this line) */
