/* Generated By:JJTree&JavaCC: Do not edit this line. MiniLangConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniLangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int ID = 9;
  /** RegularExpression Id. */
  int NUMBER = 10;
  /** RegularExpression Id. */
  int FLOAT_NUM = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"int\"",
    "\"float\"",
    "<ID>",
    "<NUMBER>",
    "<FLOAT_NUM>",
    "\"=\"",
    "\";\"",
    "\"+\"",
  };

}
